steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - ai_assistant
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}
images:
  - ${_IMAGE}
